# Generated by Django 3.0.3 on 2020-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
