# Generated by Django 3.0.3 on 2020-02-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumb',
            new_name='image',
        ),
    ]
